# Generated by Django 4.2.8 on 2024-05-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositproducts',
            name='views_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='views_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
